### PR TITLE
fixed#17-[FEAT] : User suggestions block

### LINKED ISSUE #17: [FEAT] : User suggestions block.
Description : Let's enhance Communet-Extension with User suggestions block! This feature will let users to suggest /give ideas about the improvements of communet website. It's all about making our experience smoother and more enjoyable.

Proposed Implementation:
1.Develop a block where input could be given by the user.
2.Make that part as a suggestion box that could give us new ideas from the customers/users of the website.
3.Save all the inputs given by users and store the data.

Afterwards , we , The developers need to take out insightful ideas from users and should work on it.

If you have any ideas please mention them in the comments . lets add it up.

Can't wait to hear your thoughts! Give us a thumbs up 👍 if you're excited about this addition!

Together, let's make Communet-Extension awesome! 🚀

### PR DESCRIPTION
**Pull request by anglerfishlyy**
fixes #17

I did  develop a _block_ where input could be given by the user.
I made a suggestion box that could give us new ideas/ suggestions  from the customers/users of the website.

Before this _suggestion box_ , i did add information about communet website .(what it does and what's it for).

The thank-giving note that  will be generated after clicking submit button will disappear in 5 seconds.

I hope you like it . Your FEEDBACK is appreciated.

### CODE REVIEW

**Comment by anglerfishlyy** [comment]
I hope that you will label its level  soon!
Thank you.

**Comment by Ayush-Vish** [comment]
LGTM !

**Comment by anglerfishlyy** [comment]
please, assign @anglerfishlyy in this PR as it would not count towards leaderboard of GSSOC'24.

**Pull request merged**
